## CEBD 1260 Introduction to big data and machine learning

## Session 2: General methodologies in machine learning

in this notebook, we will practice general methods of machine learning 

NOTE: for each activity below, please refer and correspond with our course slides

Instructor: Yimin Nie

email: ymnie888@gmail.com

#### Submission of your assignments:

each assignment is given in this notebook, please complete them by creating another jupyter notebook and submit on dropbox

## import important libs

In [4]:
import numpy as np   # import numpy
import pandas as pd  # import pandas
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Activity 1:  read your data, split input and target variables for your data

In [5]:
# DATA_PATH
DATA_PATH = r'C:\Users\Armin Nikzad\Desktop\fatima concordia\Machine Learning'
# DATA_PATH = r'C:\\Users\\enxxmnx\\OneDrive - Ericsson AB\\workspace\\training\\data\\city_bike_share' # this is also working


In [6]:
df = pd.read_csv((DATA_PATH+r'\train_users_2.csv'))
# df = pd.read_csv(os.path.join(DATA_PATH,'train.csv'))

In [7]:
#get some info from data frame
print(df.shape)

(213451, 16)


In [8]:
# check the data 
df.head()
# df.head(3)
# df.tail()

id date_account_created  timestamp_first_active date_first_booking  \
0  gxn3p5htnn           2010-06-28          20090319043255                NaN   
1  820tgsjxq7           2011-05-25          20090523174809                NaN   
2  4ft3gnwmtx           2010-09-28          20090609231247         2010-08-02   
3  bjjt8pjhuk           2011-12-05          20091031060129         2012-09-08   
4  87mebub9p4           2010-09-14          20091208061105         2010-02-18   

      gender   age signup_method  signup_flow language affiliate_channel  \
0  -unknown-   NaN      facebook            0       en            direct   
1       MALE  38.0      facebook            0       en               seo   
2     FEMALE  56.0         basic            3       en            direct   
3     FEMALE  42.0      facebook            0       en            direct   
4  -unknown-  41.0         basic            0       en            direct   

  affiliate_provider first_affiliate_tracked signup_app first_device_type  \
0             direct               untracked        Web       Mac Desktop   
1             google               untracked        Web       Mac Desktop   
2             direct               untracked        Web   Windows Desktop   
3             direct               untracked        Web       Mac Desktop   
4             direct               untracked        Web       Mac Desktop   

  first_browser country_destination  
0        Chrome                 NDF  
1        Chrome                 NDF  
2            IE                  US  
3       Firefox               other  
4        Chrome                  US

In [9]:
df.info() # this give you more infor about data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213451 entries, 0 to 213450
Data columns (total 16 columns):
id                         213451 non-null object
date_account_created       213451 non-null object
timestamp_first_active     213451 non-null int64
date_first_booking         88908 non-null object
gender                     213451 non-null object
age                        125461 non-null float64
signup_method              213451 non-null object
signup_flow                213451 non-null int64
language                   213451 non-null object
affiliate_channel          213451 non-null object
affiliate_provider         213451 non-null object
first_affiliate_tracked    207386 non-null object
signup_app                 213451 non-null object
first_device_type          213451 non-null object
first_browser              213451 non-null object
country_destination        213451 non-null object
dtypes: float64(1), int64(2), object(13)
memory usage: 26.1+ MB


In [10]:
des = df.describe() # describe the statistical property of the data
des

timestamp_first_active            age    signup_flow
count            2.134510e+05  125461.000000  213451.000000
mean             2.013085e+13      49.668335       3.267387
std              9.253717e+09     155.666612       7.637707
min              2.009032e+13       1.000000       0.000000
25%              2.012123e+13      28.000000       0.000000
50%              2.013091e+13      34.000000       0.000000
75%              2.014031e+13      43.000000       0.000000
max              2.014063e+13    2014.000000      25.000000

In [12]:
# get input and target from your data, X is the input, y is the target
y = df['age'].values# define target 

In [13]:
# get a full list of features we will use for input
features = [f for f in df.columns.values if f not in ['age','signup']] 
print(features)

['id', 'date_account_created', 'timestamp_first_active', 'date_first_booking', 'gender', 'signup_method', 'signup_flow', 'language', 'affiliate_channel', 'affiliate_provider', 'first_affiliate_tracked', 'signup_app', 'first_device_type', 'first_browser', 'country_destination']


In [14]:
X = df[features] # get X

In [15]:
print(X.shape,len(y))

(213451, 15) 213451


In [16]:
X.head()

id date_account_created  timestamp_first_active date_first_booking  \
0  gxn3p5htnn           2010-06-28          20090319043255                NaN   
1  820tgsjxq7           2011-05-25          20090523174809                NaN   
2  4ft3gnwmtx           2010-09-28          20090609231247         2010-08-02   
3  bjjt8pjhuk           2011-12-05          20091031060129         2012-09-08   
4  87mebub9p4           2010-09-14          20091208061105         2010-02-18   

      gender signup_method  signup_flow language affiliate_channel  \
0  -unknown-      facebook            0       en            direct   
1       MALE      facebook            0       en               seo   
2     FEMALE         basic            3       en            direct   
3     FEMALE      facebook            0       en            direct   
4  -unknown-         basic            0       en            direct   

  affiliate_provider first_affiliate_tracked signup_app first_device_type  \
0             direct               untracked        Web       Mac Desktop   
1             google               untracked        Web       Mac Desktop   
2             direct               untracked        Web   Windows Desktop   
3             direct               untracked        Web       Mac Desktop   
4             direct               untracked        Web       Mac Desktop   

  first_browser country_destination  
0        Chrome                 NDF  
1        Chrome                 NDF  
2            IE                  US  
3       Firefox               other  
4        Chrome                  US

#### Assignment 1: 

please read and split input and output for your own project data and understanding in details

## Activity 2:  identify categorical and numerical features 

In [17]:
# print data type for each feature
for f in features:
    print(" {}: {}".format(f,df[f].dtype))

 id: object
 date_account_created: object
 timestamp_first_active: int64
 date_first_booking: object
 gender: object
 signup_method: object
 signup_flow: int64
 language: object
 affiliate_channel: object
 affiliate_provider: object
 first_affiliate_tracked: object
 signup_app: object
 first_device_type: object
 first_browser: object
 country_destination: object


In [18]:
#pickup all features what are categorical
cat_features = []
for f in features:
    if str(df[f].dtype) == 'object':
        cat_features.append(f)
print(cat_features)

['id', 'date_account_created', 'date_first_booking', 'gender', 'signup_method', 'language', 'affiliate_channel', 'affiliate_provider', 'first_affiliate_tracked', 'signup_app', 'first_device_type', 'first_browser', 'country_destination']


DISCUSSIN: is it true above?? what are categorical features you think?

In [19]:
# sometimes we need to really see if one feature is categorical based on our domain knowledge or common sense
cat_features = []
for f in features:
    if str(df[f].dtype) in ['object','int64']:
        cat_features.append(f)
print(cat_features)

['id', 'date_account_created', 'timestamp_first_active', 'date_first_booking', 'gender', 'signup_method', 'signup_flow', 'language', 'affiliate_channel', 'affiliate_provider', 'first_affiliate_tracked', 'signup_app', 'first_device_type', 'first_browser', 'country_destination']


#### Assignment 2: 

please identify categorical features for your own data, you need to use some coding and your own understanding from the data

## Activity 3:  split total data by train, test and validation

In [29]:
from sklearn.model_selection import train_test_split

In [21]:
# split 20% data as test data
train_X,test_X,train_y,test_y = train_test_split(X,y,shuffle=True,random_state=2019,test_size=0.2)
print(train_X.shape,test_X.shape,len(train_y),len(test_y))

(170760, 15) (42691, 15) 170760 42691


In [22]:
# split another 20% data as valid data, NOTE that you cannot touch test data again
train_X,valid_X,train_y,valid_y = train_test_split(train_X,train_y,shuffle=True,random_state=668,test_size=0.2)
print(train_X.shape,valid_X.shape,len(train_y),len(valid_y))

(136608, 15) (34152, 15) 136608 34152


#### Assignment 3: 

please split your own project data train,valid,test by 20%,25% from the total data set

## Activity 4: split overall data set using cross validation strategies

In [23]:
from sklearn.model_selection import KFold,StratifiedKFold

In [24]:
kf = KFold(n_splits=5)
for train_idx,valid_idx in kf.split(X,y):
    print(train_idx,valid_idx)

[ 42691  42692  42693 ... 213448 213449 213450] [    0     1     2 ... 42688 42689 42690]
[     0      1      2 ... 213448 213449 213450] [42691 42692 42693 ... 85378 85379 85380]
[     0      1      2 ... 213448 213449 213450] [ 85381  85382  85383 ... 128068 128069 128070]
[     0      1      2 ... 213448 213449 213450] [128071 128072 128073 ... 170758 170759 170760]
[     0      1      2 ... 170758 170759 170760] [170761 170762 170763 ... 213448 213449 213450]


In [25]:
for train_idx,valid_idx in kf.split(X,y):
    train_X = X.loc[train_idx]
    train_y = y[train_idx]
    
    valid_X = X.loc[valid_idx]
    valid_y = y[valid_idx]

#### Assignment 4: 

practice cross validation split by your own data

## Activity 5: practice different loss functions provided by sklearn toolkit


In [26]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,log_loss

In [27]:
x = [0.4,0.7,1.5,2.9]
x_hat = [0.3,0.67,1.6,2.87]
mean_absolute_error(x,x_hat)

0.06499999999999996

In [28]:
x=[1,0,1,0,0,0,1,1,0,0,0]
x_hat =[0.98,0.12,0.86,0.04,0.004,0.01,0.998,0.976,0.005,0.025,0.017]
log_loss(x,x_hat)

0.0388645931105278

#### Assignment 5: 

refer the math defination of loss function in our slides and try to understand how to code them in sklearn